esp_toml_version = 1.0

firmware_images_url = "https://embedded.plode.org/v2/bins/"

supported_apps = ["PLAYCOMPUTER","ROBOKI","ZING0", "ZING1","HEXAPOD", "CRAWLEE8","4DOF", "OID_PEN", "PLICKER", "KLAW", "TOY_ROBOTIC_ARM", "3D_PRINTER_MB", "3D_PRINTER_DISPALY","TEST", "DS_CALIBRATE", "PEECEE_PRO", "PLAYCOMPUTER_TEST", "ROBOKI_TEST", "AI_MODULE", "ATR_H2", "2D-PLOTTER", "TOKI", "ATR_H2_TEST", "TOKI_TEST", "LOGIKI_TEST", "LOGIKI","MOKI","MOKI_TEST","JUNO","JUNO_TEST","MASTO","MASTO_TEST","POKI","POKI_TEST","SNAPPY-DONGLE", "ZING3","CRAWLEE3","TOKI_P", "EYANTRA", "AUTOKI_DEMO", "AUTOKI", "AI_1_ACC", "ZING_AI_HEAD", "JOYSTICK", "ZING3_0", "ZING2_0", "FIREPEN2D", "PIANO", "AI_0_ACC", "SNAPPY_DONGLE"]

[PLAYCOMPUTER]
chipsets = ["ESP32S3"]
image.esp32 = "playcomputer0.1/playcomputer0.1.bin"
#image.esp32-s3 = "playcomputer/playcomputer.bin"
image.esp32s3 = "PLAYCOMPUTER/PC1.0.10.0-dev.20251229-160056/PLAYCOMPUTER-GRB-PC1.0.10.0-dev.20251229-160056.bin"

# Optional: This should be a publicly accessible URL of the application configuration markdown file
# The markdown file will display the application configuration.
# It might include details such as the revisions of esp-idf, esp-matter, etc. or any other application configuration
config_readme_url = "<APP_CONFIG_README_FILE_URL>"

[ROBOKI]
chipsets = ["ESP32H2"]
image.esp32-h2 = "roboki/roboki.bin"
image."" = "Roboki/RB1.0.4.0-dev.20251223-131600/Roboki-Standard-RB1.0.4.0-dev.20251223-131600.bin"
image.esp32h2 = "Roboki/RB1.0.4.0-dev.20251223-134436/Roboki-Standard-RB1.0.4.0-dev.20251223-134436.bin"


[ZING0]
chipsets = ["ESP32"]
image.esp32 = "zing0.1/zing0.1.bin"


[ZING1]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "zing/zing.bin"
image.esp32-s3 = "zing2.0/zing2.0.bin"


[HEXAPOD]
chipsets = ["ESP32","ESP32-S3"]
image.esp32 = "crawlee1.0/crawlee1.0.bin"
image.esp32-s3 = "crawlee2.0/crawlee2.0.bin"


[CRAWLEE8]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "crawlee2.1/crawlee2.1.bin"


[4DOF]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "4dof_zing/4dof_zing.bin"


[OID_PEN]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "oid_pen/oid_pen.bin"


[PLICKER]
chipsets = ["ESP32-C2"]
image.esp32-h2 = "plicker/plicker.bin"


[KLAW]
chipsets = ["ESP32S3"]
image.esp32-s3 = "klaw/klaw.bin"
image."" = "Klaw/KW1.0.3.0-dev.20251223-131544/Klaw-Standard-KW1.0.3.0-dev.20251223-131544.bin"
image.esp32s3 = "Klaw/KW1.0.3.0-dev.20251223-134624/Klaw-Standard-KW1.0.3.0-dev.20251223-134624.bin"


[TOY_ROBOTIC_ARM]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "toy-robotic-arm/toy-robotic-arm.bin"


[3D_PRINTER_MB]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "3dprinter/3dprinter.bin"


[3D_PRINTER_DISPALY]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "3dprinter_disp/3dprinter_disp.bin"


[TEST]
chipsets = ["ESP32","ESP32-S3","ESP32-H2","ESP32-C2","ESP32-C3"]
image.esp32 = "test-firmware/esp32/test-firmware.bin"
image.esp32-s3 = "test-firmware/esp32s3/test-firmware.bin"
image.esp32-h2 = "test-firmware/esp32h2/test-firmware.bin"
image.esp32-c2 = "test-firmware/esp32c2/test-firmware.bin"
image.esp32-c3 = "test-firmware/esp32c3/test-firmware.bin"


[DS_CALIBRATE]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "ds_servo_calibrate/ds_servo_calibrate.bin"


[PEECEE_PRO]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "peeceepro/peeceepro.bin"


[PLAYCOMPUTER_TEST]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "playcomputer_test/playcomputer.bin"


[ROBOKI_TEST]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "roboki_test/roboki.bin"


[AI_MODULE]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "pc_ai_acc/pc_ai_acc.bin"

[ATR_H2]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "atr_h2/atr_h2.bin"


[2D-PLOTTER]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "2d-plotter/2d-plotter.bin"

[TOKI]
chipsets = ["CH592"]
image.ch592 = "TOKI/TK1.0.1.0TK1.0.1.0-dev.20260109-120014/TOKI-Standard-TK1.0.1.0TK1.0.1.0-dev.20260109-120014.hex"
image.ch572 = "TOKI/TK1.0.1.0TK1.0.1.0-dev.20251223-133819/firmware_info.json"

[ATR_H2_TEST]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "atr_test/atr_h2.bin"

[TOKI_TEST]
chipsets = ["CH592"]
image.ch592 = "toki_test_firmware/toki.hex"

[LOGIKI_TEST]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "logiki_test/logiki.bin"

[LOGIKI]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "logiki/logiki.bin"

[MOKI_TEST]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "moki_test/moki.bin"

[MOKI]
chipsets = ["ESP32S3"]
image.esp32-s3 = "moki/moki.bin"
image."" = "Moki/MK1.0.1.0-dev.20251223-131614/Moki-Standard-MK1.0.1.0-dev.20251223-131614.bin"
image.esp32s3 = "Moki/MK1.0.1.0-dev.20251223-134629/Moki-Standard-MK1.0.1.0-dev.20251223-134629.bin"

[JUNO_TEST]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "juno_test/juno.bin"

[JUNO]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "juno/juno.bin"

[MASTO_TEST]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "masto_test/masto.bin"

[MASTO]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "masto/masto.bin"

[POKI_TEST]
chipsets = ["CH592"]
image.ch592 = "poki_test/poki.bin"

[POKI]
chipsets = ["CH592"]
image.ch592 = "POKI/PK1.0.1.0-dev.20260114-165035/POKI-Standard-PK1.0.1.0-dev.20260114-165035.hex"
image.ch572 = "POKI/PK1.0.1.0-dev.20251219-180330/firmware_info.json"

[SNAPPY-DONGLE]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "snappy-dongle/snappy-dongle.bin"


[ZING3]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "zing3.0/zing3.0.bin"


[CRAWLEE3]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "crawlee3.0/crawlee3.0.bin"


[TOKI_P]
chipsets = ["CH592"]
image.ch592 = "toki_p/toki_p.hex"


[EYANTRA]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "eyantra/eyantra.bin"

[AUTOKI_DEMO]
chipsets = ["ESP32"]

[AUTOKI_DEMO.image]
esp32 = "AUTOKI_demo/AK1.0.1.0/AUTOKI-AK1.0.0.0-dev.20251113-130616.bin"

[AUTOKI]
chipsets = ["ESP32H2"]

[AUTOKI.image]
esp32h2 = "AUTOKI/AK1.0.0.0-dev.20251113-182931/AUTOKI-standard-AK1.0.0.0-dev.20251113-182931.bin"

[AI_1_ACC]
chipsets = ["ESP32S3"]

[AI_1_ACC.image]
esp32s3 = "AI-1_ACC/AI1.0.3.0-dev.20251229-160602/AI-1_ACC-Standard-AI1.0.3.0-dev.20251229-160602.bin"
"" = "AI-1_ACC/AI1.0.3.0-dev.20251223-131718/AI-1_ACC-Standard-AI1.0.3.0-dev.20251223-131718.bin"

[ZING_AI_HEAD]
chipsets = ["ESP32S3"]

[ZING_AI_HEAD.image]
"" = "ZING_AI_HEAD/ZAI1.0.1.0-dev.20251223-131203/ZING_AI_HEAD-Standard-ZAI1.0.1.0-dev.20251223-131203.bin"
esp32s3 = "ZING_AI_HEAD/ZAI1.0.1.0-dev.20260114-190538/ZING_AI_HEAD-Standard-ZAI1.0.1.0-dev.20260114-190538.bin"

[JOYSTICK]
chipsets = ["CH572"]

[JOYSTICK.image]
ch572 = "JOYSTICK/JY1.0.1.0-dev.20251223-133442/firmware_info.json"

[ZING3_0]
chipsets = ["ESP32S3"]

[ZING3_0.image]
"" = "Zing3.0/ZG3.0.1.0-dev.20251223-131357/Zing3.0-Standard-ZG3.0.1.0-dev.20251223-131357.bin"
esp32s3 = "Zing3.0/ZG3.0.1.0-dev.20251223-133941/Zing3.0-Standard-ZG3.0.1.0-dev.20251223-133941.bin"

[ZING2_0]
chipsets = ["ESP32S3"]

[ZING2_0.image]
"" = "ZING2.0/ZG2.1.6.0-dev.20251223-131529/ZING2.0-NORMAL_ULTRASONIC-ZG2.1.6.0-dev.20251223-131529.bin"
esp32s3 = "ZING2.0/ZG2.1.6.0-dev.20251223-134431/ZING2.0-NORMAL_ULTRASONIC-ZG2.1.6.0-dev.20251223-134431.bin"

[FIREPEN2D]
chipsets = ["ESP32S3"]

[FIREPEN2D.image]
"" = "Firepen2D/2D1.0.1.0-dev.20251223-131635/Firepen2D-Standard-2D1.0.1.0-dev.20251223-131635.bin"
esp32s3 = "Firepen2D/2D1.0.1.0-dev.20251223-135704/Firepen2D-Standard-2D1.0.1.0-dev.20251223-135704.bin"

[PIANO]
chipsets = ["CH572"]

[PIANO.image]
ch572 = "PIANO/PI1.0.1.0-dev.20251223-182631/PIANO-Standard-PI1.0.1.0-dev.20251223-182631.hex"

[AI_0_ACC]
chipsets = ["ESP32S3"]

[AI_0_ACC.image]
esp32s3 = "AI_0_ACC/AI0.0.0.1-dev.20260114-144932/AI_0_ACC-Standard-AI0.0.0.1-dev.20260114-144932.bin"

[SNAPPY_DONGLE]
chipsets = ["ESP32S3"]

[SNAPPY_DONGLE.image]
esp32s3 = "snappy-dongle/SD1.0.1.0-dev.20260106-163453/snappy-dongle-Standard-SD1.0.1.0-dev.20260106-163453.bin"
